# [[LLM-ENHANCEMENT]] This configuration is updated to align with SYSTEM_OPERATIONS_MANUAL.md
# and uses the standard 'docs' directory.

# Core project planning documents.
core_documents:
  prd: docs/prd.md
  architecture: docs/architecture.md
  # The system will be taught to generate and then reference these.
  tech_stack: docs/architecture/tech-stack.md
  coding_standards: docs/architecture/coding-standards.md
  api_endpoints: docs/architecture/api-endpoints.md

# Files that are essential for development agents to have in their context window.
devLoadAlwaysFiles:
  - docs/architecture/tech-stack.md
  - docs/architecture/coding-standards.md
  - docs/architecture/api-endpoints.md

# Settings for sharding large documents.
sharding:
  prd:
    enabled: true
    location: docs/prd_shards/
    epic_pattern: epic-{n}*.md
  architecture:
    enabled: true
    location: docs/architecture_shards/

# Debugging and logging settings
logging:
  devDebugLog: .ai/debug-log.md
  agentCoreDump: .ai/core-dump{n}.md
