# This file is used by the Stigmergy installer.
# It defines supported IDEs for configuration.
# The installer logic is now mostly dynamic, but this provides a map for setup scripts.
ide-configurations:
  roo:
    name: Roo Code (VS Code Extension)
    format: custom-modes
    file: .roomodes
    instructions: |
      # To use Stigmergy agents in Roo Code:
      # 1. Open this project directory in VS Code with the Roo Code extension.
      # 2. The custom modes defined in .roomodes will be available automatically.
      # 3. Select any 'stigmergy-{agent}' mode (e.g., "stigmergy-master").
      # 4. The AI will adopt that agent's full personality and capabilities.
  cursor:
    name: Cursor
    format: mdc-rules
    file: .cursor/rules
    instructions: |
      # Support for Cursor can be added by creating .mdc rule files.
      # This installer currently prioritizes Roo Code.
---
